import { GoogleGenAI } from "@google/genai";

export const processImage = async (
  targetPersonBase64: string,
  clothingBase64: string,
  options: {
    changeClothes: boolean;
    changeBackground: boolean;
    customScenario?: string;
  }
) => {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });
  
  let prompt = "You are a professional fashion AI editor. ";
  
  if (options.changeClothes) {
    prompt += "CRITICAL: You MUST preserve the person's face, identity, facial features, body shape, and exact proportions from the first image. Do NOT alter their physical appearance. Replace the person's ENTIRE outfit (including top, bottom, and any other visible clothing) with the clothing shown in the second image. If the second image shows a suit, dress, or a set of clothes, apply the WHOLE set realistically onto the person's body. The fit should follow the body contours of the person in the first image perfectly. ";
  } else {
    prompt += "Focus on the person in the first image. ";
  }

  if (options.changeBackground) {
    prompt += "Replace the background with a professional, organic, and aesthetically pleasing environment that provides a nice contrast to the subject and their clothing, making them stand out visually. ";
  }

  if (options.customScenario) {
    prompt += `Additional instructions: ${options.customScenario}. `;
  }

  if (!options.changeClothes && !options.changeBackground && !options.customScenario) {
    prompt += "Enhance the overall quality of the first image while keeping the person exactly as they are.";
  }

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: {
      parts: [
        {
          inlineData: {
            data: targetPersonBase64.split(',')[1],
            mimeType: "image/png",
          },
        },
        {
          inlineData: {
            data: clothingBase64.split(',')[1],
            mimeType: "image/png",
          },
        },
        { text: prompt },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the AI.");
};
